[package]
name = "paillier"
version = "0.1.0"
authors = ["Connor OHara <chuckhead7@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
paillier = { version = "0.2" }
threshold-secret-sharing = "0.2"
